from flask import Flask, render_template, request, jsonify, send_file
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os
import textwrap

app = Flask(__name__)

GENERATED_DIR = "generated"
os.makedirs(GENERATED_DIR, exist_ok=True)


def create_document(document_type, parties, effective_date, terms):
    return f"""
{document_type.upper()}

LEGAL DOCUMENT

Effective Date: {effective_date}

PARTIES
{parties}

TERMS AND CONDITIONS
{terms}

GENERAL AGREEMENT

The parties acknowledge that they have read and understood
the terms and conditions of this document.

CONFIDENTIALITY

The parties agree to maintain confidentiality of information
exchanged under this agreement.

TERMINATION

Either party may terminate this agreement by providing
written notice, subject to the applicable terms.

DISPUTE RESOLUTION

Any dispute should first be resolved through mutual discussion.

SIGNATURES

Party 1: ______________________________

Signature: ____________________________

Date: _________________________________


Party 2: ______________________________

Signature: ____________________________

Date: _________________________________


Generated by LegalEaseAI
AI-Powered Legal Document Generator
""".strip()


def create_pdf(document, filename):
    path = os.path.join(GENERATED_DIR, filename)

    pdf = canvas.Canvas(path, pagesize=A4)

    width, height = A4
    x = 50
    y = height - 50

    for line in document.splitlines():

        if not line.strip():
            y -= 12
            continue

        if y < 50:
            pdf.showPage()
            y = height - 50

        if line.strip().isupper():
            pdf.setFont("Helvetica-Bold", 11)
        else:
            pdf.setFont("Helvetica", 10)

        wrapped = textwrap.wrap(line.strip(), width=90)

        for part in wrapped:
            if y < 50:
                pdf.showPage()
                y = height - 50

            pdf.drawString(x, y, part)
            y -= 14

    pdf.save()

    return path


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/api/generate", methods=["POST"])
def generate():

    try:
        data = request.get_json()

        if not data:
            return jsonify({
                "success": False,
                "error": "No data received"
            }), 400

        document_type = data.get("documentType", "").strip()
        parties = data.get("parties", "").strip()
        effective_date = data.get("effectiveDate", "").strip()
        terms = data.get("terms", "").strip()

        if not document_type:
            return jsonify({
                "success": False,
                "error": "Document type is required"
            }), 400

        if not parties:
            return jsonify({
                "success": False,
                "error": "Parties are required"
            }), 400

        if not effective_date:
            effective_date = datetime.now().strftime("%d/%m/%Y")

        if not terms:
            return jsonify({
                "success": False,
                "error": "Terms and conditions are required"
            }), 400

        document = create_document(
            document_type,
            parties,
            effective_date,
            terms
        )

        filename = "LegalEaseAI_Document.pdf"

        create_pdf(document, filename)

        return jsonify({
            "success": True,
            "document": document,
            "download_url": "/download/" + filename
        })

    except Exception as error:
        return jsonify({
            "success": False,
            "error": str(error)
        }), 500


@app.route("/download/<filename>")
def download(filename):

    path = os.path.join(GENERATED_DIR, filename)

    if not os.path.exists(path):
        return jsonify({
            "error": "File not found"
        }), 404

    return send_file(
        path,
        as_attachment=True,
        download_name=filename
    )


@app.route("/health")
def health():
    return jsonify({
        "status": "ok",
        "application": "LegalEaseAI"
    })


if __name__ == "__main__":

    print("=" * 50)
    print("LegalEaseAI")
    print("AI-Powered Legal Document Generator")
    print("=" * 50)
    print("Server: http://127.0.0.1:8080")
    print("=" * 50)

    app.run(
        host="0.0.0.0",
        port=8080,
        debug=True
    )
